DROP DATABASE IF EXISTS pet_clinic;
CREATE DATABASE IF NOT EXISTS pet_clinic;
USE pet_clinic;

CREATE TABLE clinic(
clinicNo INT PRIMARY KEY,
clinicName VARCHAR(100) NOT NULL
-- managerNo INT NOT NULL,
-- FOREIGN KEY (managerNo) REFERENCES staff(staffNo) 
-- 	ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE staff(
staffNo INT AUTO_INCREMENT PRIMARY KEY,
staffFName VARCHAR(100) NOT NULL,
staffLName VARCHAR(100),
clinicNo INT NOT NULL,
FOREIGN KEY(clinicNo) REFERENCES clinic(clinicNo) 
ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE staff_manager(
clinicNo INT NOT NULL,
staffNo INT NOT NULL,
PRIMARY KEY(clinicNo, staffNo),
FOREIGN KEY(clinicNo) REFERENCES clinic(clinicNo)
ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY(staffNo) REFERENCES staff(staffNo)
ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE pet_owner(
ownerNo INT AUTO_INCREMENT,
ownerName VARCHAR(100),
clinicNo INT,
PRIMARY KEY (ownerNo),
FOREIGN KEY (clinicNo) REFERENCES clinic(clinicNo) 
	ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE pet(
petNo INT PRIMARY KEY,
petName VARCHAR(40),
ownerNo INT,
clinicNo INT,
FOREIGN KEY (clinicNo) REFERENCES clinic(clinicNo) 
	ON UPDATE RESTRICT ON DELETE RESTRICT,
FOREIGN KEY (ownerNo) REFERENCES pet_owner(ownerNo) 
	ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE examination(
examNo INT PRIMARY KEY,
staffNo INT NOT NULL,
petNo INT NOT NULL,
FOREIGN KEY (staffNo) REFERENCES staff(staffNo) 
	ON UPDATE RESTRICT ON DELETE RESTRICT,
FOREIGN KEY (petNo) REFERENCES pet(petNo) 
	ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE treatment(
treatNo INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE pet_treatment(
examNo INT,
treatNo INT,
PRIMARY KEY(examNO, treatNO),
FOREIGN KEY (examNo) REFERENCES examination(examNo) 
	ON UPDATE RESTRICT ON DELETE RESTRICT,
FOREIGN KEY (treatNo) REFERENCES treatment(treatNo) 
	ON UPDATE RESTRICT ON DELETE RESTRICT
);

