-- 1 Select all fields and all tuples from the invoices table
-- 2 Create a calculated  payment total for the invoices table
-- 3 Return the vendor name and vendor contact name as one field (use concat)
-- 4 Return the vendor names that start with P (use LIKE)
-- 5 Return the invoice data for invoices_id from 10 to 17;
-- 6 Write a query that uses AND in the WHERE clause 
-- 7 WRITE a query that uses OR in the WHERE clause
-- 8 Order the results of invoice 10 through 17 by invoice_total
-- 9 Order the results of invoice 10 through 17 by invoice_total in descending order and credit_total in ascending order 

-- Count the number of vendors  assign the result to a variable names num_vendors (AGGREGATION )
-- Count the number of invoices per vendor 
-- Calculate the total payment by vendor, return the vendor name and the total
-- Calculate the total payment by vendor, return the vendor id  and the total payment for vendor for vendors who paid more than $100
