CREATE DATABASE IF NOT EXISTS pet_clinic;
USE pet_clinic;

CREATE TABLE clinic(
clinicNo INT PRIMARY KEY,
clinicName VARCHAR(100) NOT NULL
-- managerNo INT NOT NULL,
-- FOREIGN KEY (managerNo) REFERENCES staff(staffNo) 
-- 	ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE staff(
staffNo INT AUTO_INCREMENT PRIMARY KEY,
staffFName VARCHAR(100) NOT NULL,
staffLName VARCHAR(100),
clinicNo INT NOT NULL,
FOREIGN KEY(clinicNo) REFERENCES clinic(clinicNo) 
ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE pet_owner(
ownerNo INT AUTO_INCREMENT,
ownerName VARCHAR(100),
clinicNo INT,
PRIMARY KEY (ownerNo),
FOREIGN KEY (clinicNo) REFERENCES clinic(clinicNo) 
	ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE pet(
petNo INT AUTO_INCREMENT PRIMARY KEY,
petName VARCHAR(40),
ownerNo INT NOT NULL,
clinicNo INT,
FOREIGN KEY (clinicNo) REFERENCES clinic(clinicNo) 
	ON UPDATE RESTRICT ON DELETE RESTRICT,
FOREIGN KEY (ownerNo) REFERENCES pet_owner(ownerNo) 
	ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE examination(
examNo INT AUTO_INCREMENT PRIMARY KEY,
staffNo INT NOT NULL,
petNo INT NOT NULL,
FOREIGN KEY (staffNo) REFERENCES staff(staffNo) 
	ON UPDATE RESTRICT ON DELETE RESTRICT,
FOREIGN KEY (petNo) REFERENCES pet(petNo) 
	ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE treatment(
treatNo INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE pet_treatment(
examNo INT NOT NULL,
treatNo INT NOT NULL,
FOREIGN KEY (examNo) REFERENCES examination(examNo) 
	ON UPDATE RESTRICT ON DELETE RESTRICT,
FOREIGN KEY (treatNo) REFERENCES treatment(treatNo) 
	ON UPDATE RESTRICT ON DELETE RESTRICT
);

